---
#
# LEVEL SECTION
title: "Space Adventure - Level 0"
world-size:
  x: 10
  y: 10
background-color:
  r: 34
  g: 35
  b: 35
viewport:
  position:
    x: 0
    y: 0
  width: 10
#
# SPRITES SECTION
sprite-sheets:
#
  - id: "moving-platform"
    path: "asset_space/movingPlat_tileset16_16.png"
    slice-size:
      x: 16
      y: 16
    scaling-factor: 1
  - id: "bitmap-text"
    path: "asset_space/fontSmall-Sheet.png"
    slice-size:
      x: 5
      y: 8
    scaling-factor: 1
  - id: "single-stone"
    path: "asset_space/tile_rock_16_16.png"
    slice-size:
      x: 16
      y: 16
    scaling-factor: 1
#
# PLATFORMS SECTION
platforms:
  - id: "static-plat-1"
    sprite-sheet: "single-stone"
    size:
      x: 3
      y: 2
    position:
      x: 0
      y: 0
    tile-map: [
      0,0,0,
      0,0,0
    ]
    z-index: 0 
    ellastic-coef: 0.5
    friction-coef: 0
  - id: "static-plat-2"
    sprite-sheet: "single-stone"
    size:
      x: 6
      y: 4
    position:
      x: 7
      y: 0
    tile-map: [
      0,0,0,0,0,0,
      0,0,0,0,0,0,
      0,0,0,0,0,0,
      0,0,0,0,0,0
    ]
    z-index: 0 
    ellastic-coef: 0.5
    friction-coef: 0
  - id: "moving-plat-1"
    sprite-sheet: "moving-platform"
    size:
    ## in multiples of the Tile
      x: 3
      y: 1
    ## specificy the lower left point of the platforms base.
    ## for moving platforms its ignored - Read from
    ## key frames instead
    position:
      x: 0
      y: 0
    ## give th4e indexes of each tile, starting
    ## at the top left corner of the Platform
    tile-map: [ 0, 1, 0 ]
    z-index: 0
    ## defines the amount of velocity 
    ## that is given back to a bouncing object
    ellastic-coef: 0.5
    friction-coef: 0
    # OPTIONAL
    flip-horizontal: [ n,n,y ]

    # to define the Platform's movement,
    # we pass a sequence of key positions at certain times
    key-positions:
      - point:
          x: 3
          y: 0
        time-arrival: 0
        time-rest: 2
      - point:
          x: 5
          y: 0
        time-arrival: 4
        time-rest: 2
# END