---
#
# LEVEL SECTION
title: "Test Level"
world-size:
  x: 50
  y: 100
background-color:
  r: 255
  g: 255
  b: 235
viewport:
  position:
    x: 0
    y: 0
  width: 10
#
# SPRITES SECTION
sprite-sheets:
#
  - id: "crocboy"
    path: "asset/crocboy.png"
    slice-size:
      x: 32
      y: 32
    scaling-factor: 1
#
  - id: "candy-cotton-floor"
    path: "asset/candy-cotton-floor.png"
    slice-size:
      x: 16
      y: 16
    scaling-factor: 1
#
  - id: "bitmap-text"
    path: "asset/text2.png"
    slice-size:
      x: 8
      y: 8
    scaling-factor: 1
#
  - id: "evil-eye"
    path: "asset/olho.png"
    slice-size:
      x: 32
      y: 32
    scaling-factor: 1
#
# PLATFORMS SECTION
platforms:
  - sprite-sheet: "candy-cotton-floor"
    size:
      x: 3
      y: 2
    ## specificy the lower left point of the platforms base.
    position:
      x: 2
      y: 0
    ## give th4e indexes of each tile, starting
    ## at the top left corner of the Platform
    tile-map: [ 0, 1, 1, 
                3 ,4 ,4 ]
    
    quarter-turns-ccw: [ 0, 0, 0, 
                         0, 0, 0 ]
    
    flip-horizontal: [ n,n,n,
                       n,n,n ]
    
    flip-vertical: [ n,n,n,
                     n,n,n ]
    
    z-index: 0
    ellastic-coef: 0.1
    friction-coef: 0
  - sprite-sheet: "candy-cotton-floor"
    size:
      x: 3
      y: 4
    position:
      x: 3.5
      y: 0
    tile-map: [ 0, 1, 2, 
                3 ,4 ,5, 
                4 ,4 ,5, 
                4 ,4 ,5]

    quarter-turns-ccw: [ 0, 0, 0, 
                         0, 0, 0,
                         0, 0, 0,
                         0, 0, 0 ]

    flip-horizontal: [ n,n,n,
                       n,n,n,
                       n,n,n,
                       n,n,n ]

    flip-vertical: [ n,n,n,
                     n,n,n,
                     n,n,n,
                     n,n,n ]

    z-index: 0
    ellastic-coef: 0.1
    friction-coef: 0
#
# ACTORS
actors:
  #
  # Bad guys first
  - id: "evil-eye"
    sprite-sheet-id: "evil-eye"
    idle-animation-id: "idle"
    mass: 20
    friction-coef: 0.2
    initial-position:
      x: 1.75
      y: 3
    bounding-box:
      x: 2
      y: 2
      w: 28
      h: 28
    sprite-animations:
      - id: "idle"
        size: 4
        slice-indexes: [ 4, 3, 4, 5 ]
        slice-durations: [200,500,1000,300]
      - id: "look-right"
        size: 5
        slice-indexes: [4,3,2,1,0]
        slice-durations: [50,70,80,90,0] # 0 value means hold frame indefinetely

  - id: "evil-eye2"
    sprite-sheet-id: "evil-eye"
    idle-animation-id: "idle"
    mass: 20
    friction-coef: 0.2
    initial-position:
      x: 3.34
      y: 4
    bounding-box:
      x: 2
      y: 2
      w: 28
      h: 28
    sprite-animations:
      - id: "idle"
        size: 4
        slice-indexes: [ 4, 3, 4, 5 ]
        slice-durations: [200,500,1000,300]
      - id: "look-right"
        size: 5
        slice-indexes: [4,3,2,1,0]
        slice-durations: [50,70,80,90,0] # 0 value means hold frame indefinetely
    # END Actors

  #
  # Bad guys first
  - id: "evil-eye"
    sprite-sheet-id: "evil-eye"
    idle-animation-id: "idle"
    mass: 20
    friction-coef: 0.2
    initial-position:
      x: 6
      y: 5
    bounding-box:
      x: 2
      y: 2
      w: 28
      h: 28
    sprite-animations:
      - id: "idle"
        size: 4
        slice-indexes: [ 4, 3, 4, 5 ]
        slice-durations: [200,500,1000,300]
      - id: "look-right"
        size: 5
        slice-indexes: [4,3,2,1,0]
        slice-durations: [50,70,80,90,0] # 0 value means hold frame indefinetely


  # - id: "evil-eye"
  #   sprite-sheet-id: "evil-eye"
  #   idle-animation-id: "idle"
  #   mass: 20
  #   friction-coef: 0.2
  #   initial-position:
  #     x: 8
  #     y: 2
  #   bounding-box:
  #     x: 2
  #     y: 2
  #     w: 28
  #     h: 28
  #   sprite-animations:
  #     - id: "idle"
  #       size: 4
  #       slice-indexes: [ 4, 3, 4, 5 ]
  #       slice-durations: [200,500,1000,300]
  #     - id: "look-right"
  #       size: 5
  #       slice-indexes: [4,3,2,1,0]
  #       slice-durations: [50,70,80,90,0] # 0 value means hold frame indefinetely
  #   # END Actors
