---
#
# LEVEL SECTION
title: "Test Level"
world-size:
  x: 50
  y: 100
background-color:
  r: 255
  g: 255
  b: 235
viewport:
  position:
    x: 0
    y: 0
  width: 10
#
# SPRITES SECTION
sprite-sheets:
#
  - id: "crocboy"
    path: "asset/crocboy.png"
    slice-size:
      x: 32
      y: 32
    scaling-factor: 1
#
  - id: "candy-cotton-floor"
    path: "asset/candy-cotton-floor.png"
    slice-size:
      x: 16
      y: 16
    scaling-factor: 1
#
  - id: "bitmap-text"
    path: "asset/text2.png"
    slice-size:
      x: 8
      y: 8
    scaling-factor: 1
#
# PLATFORMS SECTION
platforms:
  - sprite-sheet: "candy-cotton-floor"
    size:
      x: 3
      y: 2
    position:
      x: 2
      y: 1
    tile-map: [ 0, 1, 2, 3 ,4 ,5 ]
    quarter-turns-ccw: [ 0, 0, 0, 0, 0, 0 ]
    flip-horizontal: [ n,n,n,n,n,n ]
    flip-vertical: [ n,n,n,n,n,n ]
    z-index: 0
  - sprite-sheet: "candy-cotton-floor"
    size:
      x: 2
      y: 8
    position:
      x: 4
      y: 3
    tile-map: [ 0, 2, 3, 5 ,3 ,5, 3, 5, 3 ,5, 3, 5, 3 ,5, 3, 5 ]
    quarter-turns-ccw: [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    flip-horizontal: [ n,n,n,n, n,n,n,n, n,n,n,n, n,n,n,n]
    flip-vertical: [ n,n,n,n, n,n,n,n, n,n,n,n, n,n,n,n]
    z-index: 0
  

